Ext.namespace('Ext.ux.layout.flexAccord');Ext.ux.layout.flexAccord.DropTarget=function(accordionPanel,cfg)
{this.accordionPanel=accordionPanel;Ext.dd.ScrollManager.register(accordionPanel.body);Ext.ux.layout.flexAccord.DropTarget.superclass.constructor.call(this,accordionPanel.bwrap.dom,cfg);};Ext.extend(Ext.ux.layout.flexAccord.DropTarget,Ext.dd.DropTarget,{_lastPos:-1,_findResizableElement:function(accordionPanel,neededHeight)
{var items=accordionPanel.items.items;var layout=accordionPanel.getLayout();var resizable=null;var notResizable=null;var overallHeight=0;var innerHeight=accordionPanel.getInnerHeight();for(var i=0,len=items.length;i<len;i++){overallHeight+=items[i].getSize().height;if(!items[i].collapsed){if(!resizable&&layout._isResizable(items[i])&&items[i].getSize().height>neededHeight){resizable=items[i];}
if(!notResizable&&!layout._isResizable(items[i])&&items[i].getSize().height>neededHeight){notResizable=items[i];}}}
if(resizable){return{item:resizable,overallHeight:overallHeight,innerHeight:innerHeight};}
return{item:notResizable,overallHeight:overallHeight,innerHeight:innerHeight};},createEvent:function(dd,e,data,pos)
{return{accordionPanel:this.accordionPanel,panel:data.panel,position:pos,data:data,source:dd,rawEvent:e,status:this.dropAllowed};},notifyEnter:function(dd,e,data)
{var dAllowed=Ext.ux.layout.flexAccord.DropTarget.superclass.notifyEnter.call(this,dd,e,data);var pId=dd.getProxy().getProxy().dom.parentNode.id;if(data._lastResizeInfo&&pId!=this.accordionPanel.body.dom.id){data._lastResizeInfo.panel.setHeight(data._lastResizeInfo.height);data._lastResizeInfo=null;}
return dAllowed;},notifyOver:function(dd,e,data)
{var xy=e.getXY()
var accordionPanel=this.accordionPanel;var px=dd.proxy;var p=null;var match=false;var pos=0;var items=accordionPanel.items;if(items){for(var len=items.length;pos<len;pos++){p=items.get(pos);var h=p.el.getHeight();if(h!==0&&(p.el.getY()+(h/2))>xy[1]){match=true;break;}}}else{pos=false;}
var overEvent=this.createEvent(dd,e,data,pos);if(accordionPanel.fireEvent('validatedrop',overEvent)!==false&&accordionPanel.fireEvent('beforedragover',overEvent)!==false){var layout=this.accordionPanel.getLayout();var proxyEl=px.getProxy();if(dd.panel.ownerCt.getId()!=accordionPanel.getId()){var resizeInfo=this._findResizableElement(accordionPanel,proxyEl.getSize().height);if(resizeInfo.item&&resizeInfo.innerHeight-resizeInfo.overallHeight<proxyEl.getSize().height){accordionPanel.doLayout();data._lastResizeInfo={height:resizeInfo.item.getSize().height,panel:resizeInfo.item};resizeInfo.item.setHeight(resizeInfo.item.getSize().height-proxyEl.getSize().height);}}
proxyEl.setWidth('auto');if(match){if(px.proxy.dom.nextSibling!=p.el.dom){px.moveProxy(p.el.dom.parentNode,p.el.dom);}}else{Ext.fly(accordionPanel.body).appendChild(proxyEl);}
this._lastPos=pos;accordionPanel.fireEvent('dragover',overEvent);return overEvent.status;}else{return overEvent.status;}},notifyDrop:function(dd,e,data,pos)
{if(this._lastPos==-1){return;}
var pos=this._lastPos;var dropEvent=this.createEvent(dd,e,data,pos);if(this.accordionPanel.fireEvent('validatedrop',dropEvent)!==false&&this.accordionPanel.fireEvent('beforedrop',dropEvent)!==false){dd.proxy.getProxy().remove();data._lastResizeInfo=null;var oldPanel=dd.panel.ownerCt;var newPanel=this.accordionPanel;var newLayout=newPanel.getLayout();var oldLayout=oldPanel.getLayout();if(oldPanel.getId()!=newPanel.getId()){oldPanel.getLayout().unregisterPanel(dd.panel,this.accordionPanel);oldPanel.remove(dd.panel,false);oldPanel.doLayout();oldPanel.getLayout().adjustHeight();};dd.panel.el.dom.parentNode.removeChild(dd.panel.el.dom);if(pos!==false){this.accordionPanel.insert(pos,dd.panel);}else{this.accordionPanel.add(dd.panel);}
(function(){this.ownerCt.getLayout().rendered=false;this.ownerCt.doLayout();if(this._wasExpanded){this.expand(false);delete this._wasExpanded;}}).defer(1,dd.panel);this.accordionPanel.fireEvent('drop',dropEvent);}
this._lastPos=-1;}});